### ISSUE TITLE
Incorrect file name being imported for constants-example.js file

### ISSUE THREAD

**Issue by rohan-malik** [RocketChat/RC4Github#105]
Hey, this is my first issue.

I found that in the file `client/src/components/Login/index.js`, the line to import 'githubClientID' from 'constants.js' file is: `import { githubClientID } from "./../../utils/constants";`. 

However there is no 'constants.js' file in the utils folder. It should be replaced with 'constants-example.js' instead.
This is the case for other files in the 'components' folder as well.

This is causing problems in running the docker image file as well on my local computer.

**Comment by dhruvjain99** [comment]
@rohan-malik This file is an example file, which you need to copy and rename as `constants.js`. It is there for new devs to know the list of constants to be set.

**Comment by rohan-malik** [comment]
Thanks @djcruz93. I made a copy of the file with the name 'constants.js' locally. Would it be useful to make a copy of the file in the GitHub repo as well? I can add the file and make a pull request if needed. Otherwise, should I close the issue?

**Comment by RonLek** [comment]
@rohan-malik creating a `constants.js` is not needed in the repo. Doing so would expose your ids and secrets to the web. The `constants-example.js` file already exists to give devs the structure of what constants they'll need to fill in to make the app work.
