### ISSUE TITLE
Ask for `webhook` permissions only instead of `repo` access

### ISSUE THREAD

**Issue by dhruvjain99** [RocketChat/RC4Github#65]
In order to follow the principle of least privileges, bare minimum permissions required for accessing private repos read-only and configuring activity for repos is webhook.

**Comment by RonLek** [comment]
The `webhooks` scope doesn't give access to private repositories and collaborators. Accessing collaborators to a repository requires `push` access to the repository (which the `webhook` scope doesn't provide.) A better solution is to use GitHub Apps for more fine-grained permissions.

Reference - https://docs.github.com/en/developers/apps/migrating-oauth-apps-to-github-apps
